In [51]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [52]:
# Load the data

X = pd.read_csv('../DATA/X_data.csv')
y = pd.read_csv('../DATA/y_data.csv').values.ravel()

In [53]:
# Chia dữ liệu

X = X.to_numpy()

X_train_origin_41, X_test_origin_41, y_train_origin_41, y_test_origin_41 = train_test_split(X, y, test_size=0.2)  #4:1
X_train_origin_73, X_test_origin_73, y_train_origin_73, y_test_origin_73 = train_test_split(X, y, test_size=0.3)  #7:3
X_train_origin_64, X_test_origin_64, y_train_origin_64, y_test_origin_64 = train_test_split(X, y, test_size=0.4)  #6:4

In [54]:
# Chuẩn hóa dữ liệu

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_origin_41 = scaler.fit_transform(X_train_origin_41)
X_test_origin_41 = scaler.fit_transform(X_test_origin_41)

X_train_origin_73 = scaler.fit_transform(X_train_origin_73)
X_test_origin_73 = scaler.fit_transform(X_test_origin_73)

X_train_origin_64 = scaler.fit_transform(X_train_origin_64)
X_test_origin_64 = scaler.fit_transform(X_test_origin_64)

In [57]:
# Sử dụng phương pháp K-fold Cross-Validation để tìm ra K tối ưu

from MODEL import MyKNN
from sklearn.model_selection import KFold

k_values = range(2, 30)
kf = KFold(n_splits=5)
mean_accuracies = []

for k in k_values:
    accuracies = []
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        
        
        

ImportError: cannot import name 'M' from 'MODEL' (unknown location)

In [58]:
# Dùng thu vien để test thử :)))

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5)

classifier.fit(X_train_origin_41, y_train_origin_41)
y_pred_origin_41_model = classifier.predict(X_test_origin_41)

classifier.fit(X_train_origin_73, y_train_origin_73)
y_pred_origin_73_model = classifier.predict(X_test_origin_73)

classifier.fit(X_train_origin_64, y_train_origin_64)
y_pred_origin_64_model = classifier.predict(X_test_origin_64)

In [59]:
print("4:1")
print(y_test_origin_41[40:50])
print(y_pred_origin_41_model[40:50])

print("\n7:3")
print(y_test_origin_73[40:50])
print(y_pred_origin_73_model[40:50])

print("\n6:4")
print(y_test_origin_64[40:50])
print(y_pred_origin_64_model[40:50])

4:1
[4 3 2 6 5 4 6 4 6 4]
[4 3 2 6 6 4 6 4 6 4]

7:3
[1 0 1 1 6 3 1 5 2 6]
[0 0 5 1 6 3 0 5 2 6]

6:4
[0 5 0 4 2 5 6 4 0 0]
[0 5 0 4 2 1 6 4 0 5]


In [ ]:
# Dùng phương pháp KNN để phân loại trên 3 tập dữ liệu gốc đã được chia với tỷ lệ khác nhau

my_clf = KNN(k=2)

my_clf.fit(X_train_origin_41, y_train_origin_41)
y_pred_origin_41 = my_clf.predict(X_test_origin_41)
print(f"4:1: \n{y_pred_origin_41[40:50]}")

my_clf.fit(X_train_origin_73, y_train_origin_73)
y_pred_origin_73 = my_clf.predict(X_test_origin_73)
print(f"7:3: \n{y_pred_origin_73[40:50]}")

my_clf.fit(X_train_origin_64, y_train_origin_64)
y_pred_origin_64 = my_clf.predict(X_test_origin_64)
print(f"6:4: \n{y_pred_origin_64[40:50]}")

In [ ]:
# Thực hiện kiểm tra Accuracy

acc_41 = np.sum(y_pred_origin_41 == y_test_origin_41) / len(y_test_origin_41)
acc_73 = np.sum(y_pred_origin_73 == y_test_origin_73) / len(y_test_origin_73)
acc_64 = np.sum(y_pred_origin_64 == y_test_origin_64) / len(y_test_origin_64)

print(f"acc_41: {acc_41}")
print(f"acc_73: {acc_73}")
print(f"acc_64: {acc_64}")

In [ ]:
# Giảm chiều dữ liệu
# Cần tìm hiểu cách PCA hoạt động như nào

from sklearn.decomposition import PCA

pca = PCA(n_components=6)

X_train_pca_41 = pca.fit_transform(X_train_origin_41)
X_test_pca_41 = pca.fit_transform(X_test_origin_41)

X_train_pca_73 = pca.fit_transform(X_train_origin_73)
X_test_pca_73 = pca.fit_transform(X_test_origin_73)

X_train_pca_64 = pca.fit_transform(X_train_origin_64)
X_test_pca_64 = pca.fit_transform(X_test_origin_64)

In [ ]:
my_clf.fit(X_train_pca_41, y_train_origin_41)
y_pred_pca_41 = my_clf.predict(X_test_pca_41)
print(f"4:1: \n{y_pred_pca_41[40:50]}")

my_clf.fit(X_train_pca_73, y_train_origin_73)
y_pred_pca_73 = my_clf.predict(X_test_pca_73)
print(f"7:3: \n{y_pred_pca_73[40:50]}")

my_clf.fit(X_train_pca_64, y_train_origin_64)
y_pred_pca_64 = my_clf.predict(X_test_pca_64)
print(f"6:4: \n{y_pred_pca_64[40:50]}")

In [ ]:
# Thực hiện kiểm tra Accuracy

acc_pca_41 = np.sum(y_pred_pca_41 == y_test_origin_41) / len(y_test_origin_41)
acc_pca_73 = np.sum(y_pred_pca_73 == y_test_origin_73) / len(y_test_origin_73)
acc_pca_64 = np.sum(y_pred_pca_64 == y_test_origin_64) / len(y_test_origin_64)

print(f"acc_41: {acc_pca_41}")
print(f"acc_73: {acc_pca_73}")
print(f"acc_64: {acc_pca_64}")